/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const th_large_outline = IconData(0xe800, fontFamily: _kFontFam);
  static const home_outline = IconData(0xe801, fontFamily: _kFontFam);
  static const th_large_1 = IconData(0xe802, fontFamily: _kFontFam);
  static const blogger = IconData(0xe803, fontFamily: _kFontFam);
  static const home = IconData(0xe804, fontFamily: _kFontFam);
  static const search = IconData(0xe805, fontFamily: _kFontFam);
  static const barcode = IconData(0xe806, fontFamily: _kFontFam);
  static const qrcode = IconData(0xe807, fontFamily: _kFontFam);
  static const facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const facebook_official = IconData(0xf230, fontFamily: _kFontFam);
}
