name: flutube
description: Flutter plugin that facilitates the embed of YT videos without using the official YT API.
version: 0.8.2
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cached_network_image: ^2.3.1
  wakelock: ^0.1.4+2
#  video_player: ">=0.7.0 <0.11.0"
  chewie: ^0.9.10
#  screen: 0.0.5
#  youtube_player_flutter: ^7.0.0+7


flutter:
#  assets:
